version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: auction-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - auction-network

  auction-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auction-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://admin:admin@mongodb:27017
      MONGODB_DATABASE: auctions
      AUCTION_DURATION: 300
      AUCTION_CHECK_INTERVAL: 10
    depends_on:
      - mongodb
    networks:
      - auction-network

volumes:
  mongodb_data:

networks:
  auction-network:
    driver: bridge
